M48
; DRILL file {KiCad 8.0.5} date 2024-10-07T10:06:29+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-07T10:06:29+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X85.725Y-60.96
X85.725Y-107.95
X187.325Y-60.96
X187.325Y-107.95
M30
